In [2]:
import pandas as pd

In [6]:
# How to create a DataFrame? 
# Method 1 -->
data1 = {
    "Name" : ["Abhishek", "Ribhav", "Rudra"],
    "Marks" : [91, 92, 93],
    "CGPA": [8, 9, 10]
}

df = pd.DataFrame(data)

print(df)
print("\n")


# Method 3 --> 
data2 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]], columns=["A", "B", "C"])
print(data2)

       Name  Marks  CGPA
0  Abhishek     91     8
1    Ribhav     92     9
2     Rudra     93    10


    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18
6  19  20  21

In [10]:
print(data2.head())         # Prints first 5 rows only
print(data2.head(2))        # Prints first 2 rows only

print(data2.tail())         # Prints last 5 rows only
print(data2.tail(2))        # Prints last 2 rows only

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
   A  B  C
0  1  2  3
1  4  5  6
    A   B   C
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18
6  19  20  21
    A   B   C
5  16  17  18
6  19  20  21

In [11]:
data2

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18
6  19  20  21

In [13]:
data2.describe()            # Gives us some meaningful insights about our data

               A          B          C
count   7.000000   7.000000   7.000000
mean   10.000000  11.000000  12.000000
std     6.480741   6.480741   6.480741
min     1.000000   2.000000   3.000000
25%     5.500000   6.500000   7.500000
50%    10.000000  11.000000  12.000000
75%    14.500000  15.500000  16.500000
max    19.000000  20.000000  21.000000

In [ ]:
data2.nunique()             # Shows the number of unique elements in each of those columns
data2['A'].unique()         # Gives the list of those unique elements

array([ 1,  4,  7, 10, 13, 16, 19])

Loading in DataFrames from Files

In [3]:
coffee = pd.read_csv('csv_data/warmup-data/coffee.csv')
# OR
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
results = pd.read_parquet('csv_data/data/results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [5]:
olympics_data = pd.read_excel('csv_data/data/olympics-data.xlsx', sheet_name="results")
olympics_data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [6]:
bios = pd.read_csv('csv_data/data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

Accessing Data with Pandas

In [7]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [10]:
coffee.sample(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
10   Saturday    Espresso          45
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15
12     Sunday    Espresso          45
8      Friday    Espresso          45
7    Thursday       Latte          30

In [ ]:
coffee.sample(10, random_state=42)      # Acts as a seed, making the output reproducible (deterministic)

          Day Coffee Type  Units Sold
9      Friday       Latte          35
11   Saturday       Latte          35
0      Monday    Espresso          25
12     Sunday    Espresso          45
5   Wednesday       Latte          25
8      Friday    Espresso          45
2     Tuesday    Espresso          30
1      Monday       Latte          15
13     Sunday       Latte          35
4   Wednesday    Espresso          35

In [30]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [31]:
print(coffee.loc[0])

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [32]:
print(coffee.loc[:5, ["Day", "Units Sold"]])
print("\n")
print(coffee.iloc[:5, [0,2]])

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25


         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

Modifying Data with loc[]

In [41]:
coffee.loc[1, "Units Sold"] = 10
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [38]:
coffee.loc[1:3, "Units Sold"] = 10
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [43]:
# For accessing only one value from a DataFrame
print(coffee.at[0,"Day"])
print(coffee.iat[0,0])

Monday
Monday

In [48]:
coffee = coffee.sort_values("Units Sold")
print(coffee)
print("\n")
coffee = coffee.sort_values("Units Sold", ascending=False)
print(coffee)

          Day Coffee Type  Units Sold
1      Monday       Latte          10
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45


          Day Coffee Type  Units Sold
12     Sunday    Espresso          45
10   Saturday    Espresso          45
8      Friday    Espresso          45
6    Thursday    Espresso          40
13     Sunday       Latte          35
11   Saturday       Latte          35
9      Friday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [49]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
12     Sunday    Espresso          45
10   Saturday    Espresso          45
8      Friday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
13     Sunday       Latte          35
11   Saturday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [52]:
# It is not recommended to use this (iterating through the DataFrame) as we can lose some performance by doing this, because what's the use of using pandas then?!
for index, rows in coffee.iterrows():
    print(index)
    print(rows["Coffee Type"])
    print("\n\n")

12
Espresso



10
Espresso



8
Espresso



6
Espresso



13
Latte



11
Latte



9
Latte



4
Espresso



7
Latte



2
Espresso



0
Espresso



5
Latte



3
Latte



1
Latte

Filtering Data

In [53]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios.loc[bios['weight_kg'] > 100, ["name", "weight_kg"]]

#                           OR 

bios[bios['weight_kg'] > 100][["name", "weight_kg"]]

                        name  weight_kg
300             Jackson Fear      125.0
524     Bernhard Schulkowski      105.0
1080          Bozhil Lozanov      133.0
1482          José Contreras      107.0
1493         Pedro Luis Lazo      107.0
...                      ...        ...
144548    Mathias Bau Hansen      108.0
144558      Oliver Lauridsen      108.0
145259      Juraj Slafkovský      102.0
145263         Marián Skupek      108.0
145459       Roberts Mamčics      105.0

[3105 rows x 2 columns]

In [61]:
bios.loc[(bios["weight_kg"] > 100) & (bios["born_country"] == "ESP"), ["name", "born_country", "weight_kg"]]

                           name born_country  weight_kg
2845              Manuel García          ESP      130.0
5601             Enrique Andreu          ESP      102.0
6583            Fernando Martín          ESP      102.0
6957             Fernando Romay          ESP      110.0
31399            Mateo Garralda          ESP      102.0
31425                Jaime Puig          ESP      105.0
33914            Santiago Ojeda          ESP      120.0
33958             Ernesto Pérez          ESP      101.0
57440         Jesús Montesdeoca          ESP      120.0
60855      José María Benavides          ESP      130.0
61236               Juan Costas          ESP      103.0
61876            Javier Hermida          ESP      120.0
62428          Domingo Manrique          ESP      104.0
63501       José Manuel Valadés          ESP      105.0
66742           Manuel Martínez          ESP      132.0
66744            David Martínez          ESP      101.0
89074         Ignacio de Miguel          ESP      111.0
89075            Roberto Dueñas          ESP      137.0
89076           Jorge Garbajosa          ESP      107.0
89080             Alfonso Reyes          ESP      111.0
92082           Rafael Trujillo          ESP      104.0
93963               Jon Tecedor          ESP      135.0
103566            Pablo Arrarte          ESP      108.0
104693            Mario Pestano          ESP      120.0
105715            Aythami Ruano          ESP      198.0
107369                Pau Gasol          ESP      115.0
107370              Iker Iturbe          ESP      108.0
107371             Felipe Reyes          ESP      109.0
107528             Manuel Colón          ESP      103.0
107531              Iker Romero          ESP      104.0
108293         Guillermo Molina          ESP      105.0
110560        Alberto Fernández          ESP      115.0
112314               Marc Gasol          ESP      122.0
112537           Rubén Garabaya          ESP      107.0
112538        Cristian Malmagro          ESP      107.0
112539            Carlos Prieto          ESP      108.0
112903              Xavi Vallès          ESP      102.0
122905            Víctor Claver          ESP      107.0
122910    Fernando San Emeterio          ESP      105.0
123025        Julen Aguinagalde          ESP      113.0
123036         Gedeón Guardiola          ESP      105.0
123038            Jorge Maqueda          ESP      102.0
123165         Hodei Mazquiarán          ESP      102.0
123792        Javier Cienfuegos          ESP      110.0
123808              Borja Vivas          ESP      139.0
130883          Carlos Tobalina          ESP      120.0
130895        Willy Hernangómez          ESP      115.0
130931         Iñaki Villanueva          ESP      103.0
130964         Alberto Munárriz          ESP      105.0
130968           Ricard Alarcón          ESP      110.0
130969             Roger Tahull          ESP      105.0
133631              Borja Vidal          ESP      110.0
138965       María Belén Toimil          ESP      102.0
139095  Miguel Sánchez-Migallón          ESP      102.0
139127         Alejandro Bustos          ESP      106.0
139132           Miguel De Toro          ESP      115.0
139134              Marcos Ruiz          ESP      102.0

In [ ]:
bios[bios["name"].str.contains("Abhishek")]                     # NOT case sensitive
bios[bios["name"].str.contains("Abhishek", case=False)]         # Case sensitive
bios[bios["name"].str.contains("Abhishek|Jadhav")]              # Regex search functionality | If we want to search multiple names   

# We can disable this regex search functionality by simply doing this -->
bios[bios["name"].str.contains("Abhishek|Jadhav", regex=False)] # This will not return anything as that particular exact string doesn't exist!

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [103]:
bios.loc[bios["born_country"].isin(["ESP", "ARG", "MEX"]) & bios.name.str.startswith("Sergio")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2413,2423,Sergio Casal,1962-09-08,Barcelona,Barcelona,ESP,Spain,186.0,75.0,NaN
2865,2877,Sergio Rey,1969-11-04,San Sebastián,Guipúzcoa,ESP,Spain,178.0,63.0,NaN
6263,6291,Sergio Holguín,1929-04-15,Ciudad Juárez,Chihuahua,MEX,Mexico,NaN,NaN,2013-01-01
8920,8968,Sergio Mangín,1973-06-28,Neuquén,Neuquén,ARG,Argentina,179.0,84.0,NaN
20924,21071,Sergio Lucchetti,1958-04-13,Buenos Aires,Ciudad Autónoma de Buenos Aires,ARG,Argentina,182.0,78.0,NaN
22745,22915,Sergio Escobedo,1931-01-10,Ciudad de México (Mexico City),Ciudad de México,MEX,Mexico,173.0,73.0,2009-05-10
24681,24870,Sergio Corino,1974-10-10,Baracaldo,Vizcaya,ESP,Spain,181.0,73.0,NaN
34692,34961,Sergio Salazar,1973-10-17,Ciudad de México (Mexico City),Ciudad de México,MEX,Mexico,176.0,89.0,NaN
34949,35220,Sergio Fernández,1967-03-27,Campana,Provincia de Buenos Aires,ARG,Argentina,186.0,90.0,NaN
46202,46549,Sergio López,1968-08-15,Barcelona,Barcelona,ESP,Spain,186.0,78.0,NaN
46226,46573,Sergio Roure,1972-09-07,Lérida,Lérida,ESP,Spain,NaN,NaN,NaN
53406,53786,Sergio Pedrerol,1969-12-16,Molíns de Rei,Barcelona,ESP,Spain,190.0,78.0,NaN
54069,54457,Sergio Ramos,1941-04-19,Ciudad de México (Mexico City),Ciudad de México,MEX,Mexico,171.0,68.0,NaN
61708,62162,Sergio González,1925-07-03,Ciudad de México (Mexico City),Ciudad de México,MEX,Mexico,173.0,75.0,2017-09-03
66736,67246,Sergio López,1968-07-22,Santa Pola,Alicante,ESP,Spain,176.0,70.0,NaN
92308,93048,Sergio Piñero,1974-11-28,Las Palmas de Gran Canaria,Las Palmas,ESP,Dominican Republic Spain,178.0,NaN,NaN
92504,93247,Sergio Ferreyra,1977-05-21,Oberá,Misiones,ARG,Argentina,182.0,80.0,NaN
104818,105844,Sergio Llopis,1978-08-18,Játiva,Valencia,ESP,Spain,180.0,78.0,NaN
110178,111387,Sergio Agüero,1988-06-02,Quilmes,Provincia de Buenos Aires,ARG,Argentina,172.0,74.0,NaN
110729,111955,Sergio Muñoz,1989-08-30,Soria,Soria,ESP,Spain,171.0,69.0,NaN
112375,113631,Sergio Romero,1987-02-22,Bernardo de Irigoyen,Santa Fe,ARG,Argentina,191.0,86.0,NaN
114495,115806,Sergio García,1989-10-09,Barcelona,Barcelona,ESP,Spain,188.0,80.0,NaN
122908,125051,Sergio Rodríguez,1986-06-12,Santa Cruz de Tenerife,Santa Cruz de Tenerife,ESP,Spain,191.0,80.0,NaN
123160,125331,Sergio Mantecón,1984-09-25,Santander,Cantabria,ESP,Spain,179.0,71.0,NaN
130892,133646,Sergio Fernández,1993-04-01,Pamplona,Navarra,ESP,Spain,186.0,78.0,NaN
130912,133666,Sergio Álvarez,1985-01-07,Avilés,Asturias,ESP,Spain,174.0,74.0,NaN
130915,133669,Sergio García,1980-01-09,Borriol,Castellón,ESP,Spain,178.0,NaN,NaN

In [ ]:
bios.query('born_city == "Rosario" & born_country == "ARG"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3307,3319,Alfredo Carlomagno,1917-10-05,Rosario,Santa Fe,ARG,Argentina,NaN,NaN,NaN
4978,4996,Francisco Risiglione,1917-01-18,Rosario,Santa Fe,ARG,Argentina,178.0,NaN,1999-07-28
5960,5986,Hugo del Vecchio,1928-02-22,Rosario,Santa Fe,ARG,Argentina,184.0,NaN,1999-09-07
6815,6848,Esteban Pérez,1969-03-26,Rosario,Santa Fe,ARG,Argentina,200.0,101.0,NaN
9116,9167,Sébastian Cuattrín,1973-09-06,Rosario,Santa Fe,ARG,Brazil,183.0,86.0,NaN
...,...,...,...,...,...,...,...,...,...,...
137116,140457,Nadia Podoroska,1997-02-10,Rosario,Santa Fe,ARG,Argentina,NaN,NaN,NaN
137137,140482,Nicolás Capogrosso,1995-01-15,Rosario,Santa Fe,ARG,Argentina,205.0,NaN,NaN
137147,140493,Ezequiel Ponce,1997-03-29,Rosario,Santa Fe,ARG,Argentina,180.0,NaN,NaN
137190,140536,Facundo Bagnis,1990-02-27,Rosario,Santa Fe,ARG,Argentina,NaN,NaN,NaN
137191,140537,Federico Coria,1992-03-09,Rosario,Santa Fe,ARG,Argentina,NaN,NaN,NaN

Adding / Removing Columns

In [ ]:
coffee = pd.read_csv('csv_data/warmup-data/coffee.csv')

In [41]:
coffee_new = coffee.copy()
coffee_new['price'] = 149

In [42]:
coffee_new
# Coffee_new is basically pointing to the same memory space as that of coffee. Hence we can see 'price' visible in coffee as well!
# If we wanted to make this separate we should've done this ->
# coffee_new = coffee.copy()

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25    149
1      Monday       Latte          15    149
2     Tuesday    Espresso          30    149
3     Tuesday       Latte          20    149
4   Wednesday    Espresso          35    149
5   Wednesday       Latte          25    149
6    Thursday    Espresso          40    149
7    Thursday       Latte          30    149
8      Friday    Espresso          45    149
9      Friday       Latte          35    149
10   Saturday    Espresso          45    149
11   Saturday       Latte          35    149
12     Sunday    Espresso          45    149
13     Sunday       Latte          35    149

In [57]:
import numpy as np
coffee_new['new_price'] = np.where(coffee_new['Coffee Type'] == 'Espresso', 149, 299)
coffee_new.drop(columns=['price'], inplace=True) 
# OR 
# coffee_new = coffee_new.drop(columns=['price'])

In [ ]:
coffee_new.rename(columns={'new_price':'price'}, inplace=True)      # Renaming columns

In [61]:
coffee_new['revenue'] = coffee_new['Units Sold'] * coffee_new['price']
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso          25     3725    149
1     Monday       Latte          15     4485    299
2    Tuesday    Espresso          30     4470    149
3    Tuesday       Latte          20     5980    299
4  Wednesday    Espresso          35     5215    149

In [62]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [63]:
bios_new = bios.copy()

In [ ]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [77]:
# Now let's do a similar thing but for birth_year (Only store the birth year!)
# But in order to deal with such 'date' related data, always convert them into datetime format!
# To do that, -->
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [ ]:
# There's no visual difference as such but if you do bios_new.info() you can see datatype, there it will be datetime!
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,birth_year,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878,1878-04-17

In [75]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  first_name     145500 non-null  object
 11  birth_year     143693 non-null  object
 12  born_datetime  143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(2), str(7)
memory usage: 21.9+ MB

In [83]:
bios_new['birth_year'] = bios_new['born_datetime'].dt.year
bios_new[['name','birth_year']]

                         name  birth_year
0       Jean-François Blanchy      1886.0
1              Arnaud Boetsch      1969.0
2                Jean Borotra      1898.0
3             Jacques Brugnon      1895.0
4                Albert Canet      1878.0
...                       ...         ...
145495      Polina Luchnikova      2002.0
145496    Valeriya Merkusheva      1999.0
145497        Yuliya Smirnova      1998.0
145498         André Foussard      1899.0
145499          Bill Phillips      1913.0

[145500 rows x 2 columns]

In [84]:
bios_new.to_csv('./csv_data/data/bios_new.csv', index=False)

In [88]:
# Now let's say we want to categorize athletes into short, avg and tall.
# So to do that, what we gotta do is - 
bios_new['Height_Category'] = bios_new['height_cm'].apply(lambda x: 'Short' if x < 165 else('Average' if  x < 185 else 'Tall'))

In [92]:
# Now what we did above the same can be done by defining functions 
def categorize_athletes(row):
    if row['height_cm'] < 165 and row['weight_kg'] <= 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 85:
        return 'Middleweight'
    else:
        return 'Heavyweight'
    
bios_new['Category'] = bios.apply(categorize_athletes, axis=1)  # 1 -> rows, 0 -> columns

In [93]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,birth_year,born_datetime,Height_Category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,1969-04-01,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,1898-08-13,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,1895-05-11,Average,Middleweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,1878-04-17,Tall,Heavyweight

Merging and Concatenating Data

In [94]:
nocs = pd.read_csv('./csv_data/data/noc_regions.csv')

In [97]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [98]:
bios_new = pd.merge(bios_new, nocs, left_on='born_country', right_on='NOC', how='left')

In [99]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,birth_year,born_datetime,Height_Category,Category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,1969-04-01,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,1898-08-13,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,1895-05-11,Average,Middleweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,1878-04-17,Tall,Heavyweight,GBR,UK,NaN

In [100]:
usa = bios_new[bios_new['born_country'] == 'USA'].copy()
gbr = bios_new[bios_new['born_country'] == 'GBR'].copy()

In [ ]:
new_df = pd.concat([usa,gbr])

In [104]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,birth_year,born_datetime,Height_Category,Category,NOC_y,region,notes
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Monique,1967.0,1967-07-22,Average,Middleweight,USA,USA,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Xóchitl,1968.0,1968-09-17,Average,Middleweight,USA,USA,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Angélica,1973.0,1973-10-03,Short,Lightweight,USA,USA,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Bert,1897.0,1897-07-01,Tall,Heavyweight,USA,USA,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Laura,1975.0,1975-01-06,Average,Middleweight,USA,USA,NaN

In [105]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [106]:
combined_df = pd.merge(results, bios_new, on='athlete_id', how='left')

In [107]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,weight_kg,died_date,first_name,birth_year,born_datetime,Height_Category,Category,NOC_y,region,notes
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN

Handling Null Values

In [126]:
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso        15.0     3725    149
1     Monday       Latte        20.0     4485    299
2    Tuesday    Espresso         NaN     4470    149
3    Tuesday       Latte         NaN     5980    299
4  Wednesday    Espresso        35.0     5215    149

In [142]:
# If you want to explicitly add NaN (Not-a-Number) in your df, then -->
coffee_new.loc[[2, 3], 'Units Sold'] = np.nan

In [127]:
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso        15.0     3725    149
1     Monday       Latte        20.0     4485    299
2    Tuesday    Espresso         NaN     4470    149
3    Tuesday       Latte         NaN     5980    299
4  Wednesday    Espresso        35.0     5215    149

In [128]:
coffee_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   12 non-null     float64
 3   revenue      14 non-null     int64
 4   price        14 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 883.0 bytes

In [143]:
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso        15.0     3725    149
1     Monday       Latte        20.0     4485    299
2    Tuesday    Espresso         NaN     4470    149
3    Tuesday       Latte         NaN     5980    299
4  Wednesday    Espresso        35.0     5215    149

In [150]:
# We can handle null values using multiple things:

# 1. Using mean()
coffee_new.fillna(coffee_new['Units Sold'].mean())

# 2. Using interpolate(), meaning it sees if there's a pattern (checks neighbours) and then accordingly it continues that pattern in the column
coffee_new['Units Sold'] = coffee_new['Units Sold'].interpolate()

# 3. Or we can simply drop those rows!
# coffee_new.dropna()

In [151]:
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso        15.0     3725    149
1     Monday       Latte        20.0     4485    299
2    Tuesday    Espresso        25.0     4470    149
3    Tuesday       Latte        30.0     5980    299
4  Wednesday    Espresso        35.0     5215    149

In [152]:
# If you want to view all the rows having an NaN value in a particular column - 
coffee_new[coffee_new['Units Sold'].isna()]

# If you want to view all the rows NOT having an NaN value in a particular column - 
coffee_new[coffee_new['Units Sold'].notna()]

          Day Coffee Type  Units Sold  revenue  price
0      Monday    Espresso        15.0     3725    149
1      Monday       Latte        20.0     4485    299
2     Tuesday    Espresso        25.0     4470    149
3     Tuesday       Latte        30.0     5980    299
4   Wednesday    Espresso        35.0     5215    149
5   Wednesday       Latte        25.0     7475    299
6    Thursday    Espresso        40.0     5960    149
7    Thursday       Latte        30.0     8970    299
8      Friday    Espresso        45.0     6705    149
9      Friday       Latte        35.0    10465    299
10   Saturday    Espresso        45.0     6705    149
11   Saturday       Latte        35.0    10465    299
12     Sunday    Espresso        45.0     6705    149
13     Sunday       Latte        35.0    10465    299

Aggregating Data

In [153]:
# Let's say you wanna find which state produces the most number of athletes!
bios[bios['born_country'] == 'IND']['born_region'].value_counts()

born_region
Punjab                                 94
Maharashtra                            56
West Bengal                            49
Haryana                                43
Uttar Pradesh                          42
Tamil Nadu                             34
Karnataka                              32
National Capital Territory of Delhi    32
Kerala                                 26
Andhra Pradesh                         23
Madhya Pradesh                         22
Rajasthan                              14
Himachal Pradesh                       10
Manipur                                10
Gujarat                                 9
Bihar                                   6
Jharkhand                               5
Assam                                   5
Jammu and Kashmir                       5
Uttarakhand                             4
Tripura                                 3
Chhattisgarh                            2
Chandigarh                              2
Goa                                     2
Nagaland                                2
Mizoram                                 1
Puducherry                              1
Sikkim                                  1
Orissa                                  1
Name: count, dtype: int64

In [155]:
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso        15.0     3725    149
1     Monday       Latte        20.0     4485    299
2    Tuesday    Espresso        25.0     4470    149
3    Tuesday       Latte        30.0     5980    299
4  Wednesday    Espresso        35.0     5215    149

In [ ]:
# Using groupby()
coffee_new.groupby(['Coffee Type'])['Units Sold'].sum()
coffee_new.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    35.714286
Latte       30.000000
Name: Units Sold, dtype: float64

In [159]:
# Pivot Table (Changing the DF however you want according to your needs (changing rows into columns and columns into rows))
pivot = coffee_new.pivot(columns='Coffee Type', index='Day', values='revenue')

In [160]:
pivot

Coffee Type  Espresso  Latte
Day
Friday           6705  10465
Monday           3725   4485
Saturday         6705  10465
Sunday           6705  10465
Thursday         5960   8970
Tuesday          4470   5980
Wednesday        5215   7475

In [ ]:
# Printing the total revenue day-wise
pivot.sum(axis=1)

Day
Friday       17170
Monday        8210
Saturday     17170
Sunday       17170
Thursday     14930
Tuesday      10450
Wednesday    12690
dtype: int64

In [164]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,birth_year,born_datetime,Height_Category,Category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,1969-04-01,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,1898-08-13,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,1895-05-11,Average,Middleweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,1878-04-17,Tall,Heavyweight,GBR,UK,NaN

In [ ]:
# Grouping athletes by the year they were born from India!
bios_new[bios_new['born_country'] == 'IND'].groupby(['birth_year']).size().reset_index().sort_values('birth_year', ascending=False)
# Basically what we are doing here is, we are grouping all the Indian athletes depending upon their 'birth year' 
# and then displaying the number of athletes born in that specific year by arranging them in a descending order.


# But doing this is over-complicating because we could've simply done value_counts()
bios_new[bios_new['born_country'] == 'IND']['birth_year'].value_counts()

     birth_year  0
121      2000.0  1
120      1999.0  1
119      1998.0  2
118      1997.0  2
117      1996.0  5
..          ... ..
4        1872.0  1
3        1869.0  1
2        1866.0  1
1        1865.0  1
0        1849.0  1

[122 rows x 2 columns]

Advanced Functionality

In [194]:
coffee_new.head()

         Day Coffee Type  Units Sold  revenue  price
0     Monday    Espresso        15.0     3725    149
1     Monday       Latte        20.0     4485    299
2    Tuesday    Espresso        25.0     4470    149
3    Tuesday       Latte        30.0     5980    299
4  Wednesday    Espresso        35.0     5215    149

In [208]:
# shift()   -   Moves data up(backwards) / down(forward) by specified number of rows
# If you want to move up (backwards) enter a negative number in the shift()

# Comparing yesterday's and today's revenue of Latte and Espresso!
coffee_new["Yesterday's revenue"] = coffee_new['revenue'].shift(2)

In [209]:
coffee_new.tail()

         Day Coffee Type  Units Sold  revenue  price  Yesterday's revenue
9     Friday       Latte        35.0    10465    299               8970.0
10  Saturday    Espresso        45.0     6705    149               6705.0
11  Saturday       Latte        35.0    10465    299              10465.0
12    Sunday    Espresso        45.0     6705    149               6705.0
13    Sunday       Latte        35.0    10465    299              10465.0

In [204]:
# rank()    -   Assigns a rank (position) to each value based on its order.

# Rank all the athletes based upon their height!
bios_new['height_rank'] = bios_new['height_cm'].rank(ascending=False)       # Tallest person gets first rank!
bios_new.sort_values(['height_rank'])[['first_name', 'height_cm', 'height_rank']].head()

      first_name  height_cm  height_rank
89070        Yao      226.0          1.0
6978     Arvydas      223.0          2.5
5781       Tommy      223.0          2.5
5673     Gunther      221.0          5.0
89075    Roberto      221.0          5.0

In [214]:
# rolling() -   Creates a moving window over data and performs calculations line mean, min, max, or sum
# cumsum()  -   Keeps on adding new values to the previous sum


# Find the no of latte's sold for the past 3 days only!
latte = coffee_new[coffee_new['Coffee Type'] == 'Latte'].copy()
latte['3Day_Coffees Sold'] = latte['Units Sold'].rolling(3).sum()

In [215]:
latte

,Day,Coffee Type,Units Sold,revenue,price,Yesterday's revenue,3Day_Coffees Sold
1,Monday,Latte,20.0,4485,299,NaN,NaN
3,Tuesday,Latte,30.0,5980,299,4485.0,NaN
5,Wednesday,Latte,25.0,7475,299,5980.0,75.0
7,Thursday,Latte,30.0,8970,299,7475.0,85.0
9,Friday,Latte,35.0,10465,299,8970.0,90.0
11,Saturday,Latte,35.0,10465,299,10465.0,100.0
13,Sunday,Latte,35.0,10465,299,10465.0,105.0